variable "BigQ-DS-dataset_id" {}
variable "BigQ-DS-friendly_name" {}
variable "BigQ-DS-description" {}
variable "BigQ-DS-location" {}
variable "BigQ-DS-default_table_expiration_ms" {}
variable "BigQ-DS-project" {}
variable "BigQ-Table-table_id" {}
variable "BigQ-Table-TP-type" {}
variable "BigQ-deletion_protection" {}
variable "schema" {}
